import Splashscreen from './Splashscreen';
import Login from './Login';
import Register from './Register';
import Home from './Home';
import Mikrotik from './Mikrotik';
import Pelanggan from './data-list';
import Pembayaran from './Pembayaran';
import Admin from './Admin';
import Addpelanggan from './Addpelanggan';
import Editpelanggan from './edit-data';
import Detailuser from './detail-user';
import Isolir from './isolir-data';
import Aktifdata from './aktif-data';
import Historipembayaran from './data-pembayaran';
import Harga from './harga';
import Tambahpaket from './Tambahpaket';
import Editpaket from './editpaket';
export {Home};
export {Splashscreen};
export {Login};
export {Register};
export {Mikrotik};
export {Pelanggan};
export {Pembayaran};
export {Admin};
export {Addpelanggan};
export {Editpelanggan};
export {Detailuser};
export {Isolir};
export {Aktifdata};
export {Historipembayaran};
export {Harga};
export {Tambahpaket};
export {Editpaket};
